apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
    namespace: demo
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample

    spec:
      containers:
      - image: swathithangaraj/sample2:latest
        name: sample
        ports:
        - containerPort: 80

