apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample
  name: sample
  namespace: demo
spec:
  ports:
  - nodePort: 30502
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample
  type: NodePort
